management:
  endpoint:
    health:
      show-details: always
server:
  port: 8888
spring:
  application:
    name: vendorsbar-config-service
  security:
    user:
      name: user
      password: 61f4d703-7115-4a5c-8409-9e4ce8360347
  cloud:
    consul:
      host: 172.24.33.114
      port: 8500
      discovery:
        prefer-ip-address: true
        tags: version=1.0
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
        healthCheckInterval: 15s
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
    config:
      server:
        git:
          uri: https://github.com/lucuicheng/vendorsbar-config.git
          search-paths: common-config,order-config,product-config
          username: lucuicheng@163.com
          password:
          basedir: ./config
